exports.cmpListPage = function(clist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>

        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th>
                            <th>Bio</th>
                            <th>Data de nascimento</th>
                            <th>Data de óbito</th>
                            <th>Periodo</th>
                            <th>Actions</th>
                        </tr>`
    for(let i=0; i < clist.length ; i++){
        pagHTML +=      `<tr>
                            <td>
                                <a href="/compositores/${clist[i].id}">${clist[i].nome}</a>
                            </td>
                            <td>${clist[i].bio}</td>
                            <td>${clist[i].dataNasc}</td>
                            <td>${clist[i].dataObito}</td>
                            <td>${clist[i].periodo.name}</td>
                            <td>
                                [<a href="/compositores/edit/${clist[i].id}">Edit</a>]
                                [<a href="/compositores/delete/${clist[i].id}">Delete</a>]
                            </td>
                        </tr>`
    }

    pagHTML +=      `</table>
                </div>

                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>`
    return pagHTML
}


exports.cmpFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Registo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Registo</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Data Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Data Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>

            </div>
        `
    
}

exports.cmpFormEditPage = function(d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Editar</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" value="${d.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${d.nome}"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${d.bio}"/>
                        <label>Data Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${d.dataNasc}"/>
                        <label>Data Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${d.dataObito}"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${d.periodo}"/>                        
                        </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}


exports.cmpPage = function(cmp, d ){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <title>${cmp.nome}</title>
            <meta charset="utf-8"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>${cmp.nome}</h1>
                </header>

                <div class="w3-container">
                    <ul class="w3-ul w3-card-4" style="width:50%">
                        <li><b>Nome: </b> ${cmp.nome}</li>
                        <li><b>Bio: </b> ${cmp.bio}</li>
                        <li><b>Data Nascimento: </b> ${cmp.dataNasc}</li>
                        <li><b>Data Óbito: </b> ${cmp.dataObito}</li>
                        <li><b>Periodo: </b> ${cmp.periodo.name}</li>
                    </ul>
                </div>
        
                <footer class="w3-container w3-teal">
                    <address>Gerado por aluno::EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</address>
                </footer>
            </div>
        </body>
    </html>`
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `<p>${d}: Error: ${errorMessage}</p>`
}